---
abstract: 'INSERT YOUR ABSTRACT HERE'
author:
  - 'Leon Timmermans <fawaka@gmail.com>'
build_requires: {}
configure_requires:
  Module::Build::Tiny: '0.039'
dynamic_config: 0
generated_by: 'App::ModuleBuildTiny version 0.046, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Build-XS-PkgConfig
provides:
  Dist::Build::XS::PkgConfig:
    file: lib/Dist/Build/XS/PkgConfig.pm
    version: '0.000'
requires:
  strict: '0'
  warnings: '0'
version: '0.000'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
